name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build Linux binaries and release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Download Go dependencies
        run: go mod download

      - name: Build for Linux ${{ matrix.goarch }}
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o dist/wugo-${{ matrix.goarch }} wugo.go

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
